"""
Store Location DocType Definition
Production-ready hierarchical location system for technical stores.
"""

doctype = {
	"name": "Store Location",
	"module": "Technical Store System",
	"custom": 1,
	"issingle": 0,
	"is_submittable": 0,
	"is_tree": 0,
	"editable_grid": 1,
	"track_changes": 1,
	"autoname": "field:location_code",
	"title_field": "location_name",
	"document_type": "Document",
	
	"fields": [
        
		{
			"fieldname": "basic_info_tab",
			"label": "Basic Information",
			"fieldtype": "Tab Break",
		},
		{
			"fieldname": "location_code",
			"label": "Location Code",
			"fieldtype": "Data",
			"reqd": 0,
			"unique": 1,
			"in_list_view": 1,
			"in_standard_filter": 1,
			"bold": 1,
			"read_only": 1,
			"description": "Auto-generated code (e.g., WH-1-A-R01-S1-B1)"
		},
		{
			"fieldname": "warehouse_name",
			"label": "Warehouse Name",
			"fieldtype": "Data",
			"reqd": 0,
			"read_only": 1,
			"depends_on": "eval:doc.location_type == 'Warehouse'",
			"description": "Auto-generated warehouse name (e.g., WH-1, WH-2, WH-3)"
		},
		{
			"fieldname": "location_name",
			"label": "Location Name",
			"fieldtype": "Data",
			"reqd": 0,
			"in_list_view": 1,
			"read_only": 1,
			"description": "Auto-generated by controller"
		},
		{
			"fieldname": "column_break_1",
			"fieldtype": "Column Break"
		},
		{
			"fieldname": "location_type",
			"label": "Location Type",
			"fieldtype": "Select",
			"options": "\nWarehouse\nZone\nRack\nShelf\nBin\nTransit\nStaging\nOther",
			"reqd": 1,
			"in_list_view": 1,
			"in_standard_filter": 1,
			"bold": 1,
			"description": "Select level in hierarchy"
		},
		{
			"fieldname": "enabled",
			"label": "Enabled",
			"fieldtype": "Check",
			"default": 1,
			"in_list_view": 1,
			"in_standard_filter": 1,
			"description": "Active locations only"
		},
		
        
		{
			"fieldname": "section_hierarchy",
			"fieldtype": "Section Break",
			"label": "Hierarchy",
			"collapsible": 1,
			"collapsed": 1
		},
		{
			"fieldname": "parent_location",
			"label": "Parent Location",
			"fieldtype": "Link",
			"options": "Store Location",
			"description": "Optional: For tree-based navigation"
		},
		{
			"fieldname": "is_group",
			"label": "Is Group Location",
			"fieldtype": "Check",
			"default": 0,
			"description": "Can contain sub-locations"
		},
		{
			"fieldname": "column_break_2",
			"fieldtype": "Column Break"
		},
		
        
		{
			"fieldname": "section_physical",
			"fieldtype": "Section Break",
			"label": "",
			"description": "",
			"depends_on": "eval:doc.location_type && doc.location_type != 'Warehouse'"
		},
        
		{
			"fieldname": "store",
			"label": "Store/Warehouse",
			"fieldtype": "Link",
			"options": "Store Location",
			"description": "Select parent warehouse (required for Zone, Rack, Shelf, Bin)",
			"reqd": 0,
			"depends_on": "eval:['Zone', 'Rack', 'Shelf', 'Bin'].includes(doc.location_type)"
		},
		{
			"fieldname": "zone",
			"label": "Zone/Area",
			"fieldtype": "Link",
			"options": "Store Location",
			"description": "Select zone within selected warehouse (required for Rack, Shelf, Bin)",
			"reqd": 0,
			"depends_on": "eval:['Rack', 'Shelf', 'Bin'].includes(doc.location_type)"
		},
		{
			"fieldname": "zone_name",
			"label": "Zone Name",
			"fieldtype": "Data",
			"reqd": 0,
			"read_only": 1,
			"depends_on": "eval:doc.location_type == 'Zone'",
			"description": "Auto-generated (e.g., Z-A, Z-B, Z-C)"
		},
		{
			"fieldname": "column_break_physical",
			"fieldtype": "Column Break"
		},
        
		{
			"fieldname": "rack",
			"label": "Rack",
			"fieldtype": "Link",
			"options": "Store Location",
			"description": "Select rack within selected zone (required for Shelf, Bin)",
			"reqd": 0,
			"depends_on": "eval:['Shelf', 'Bin'].includes(doc.location_type)"
		},
		{
			"fieldname": "rack_name",
			"label": "Rack Name",
			"fieldtype": "Data",
			"reqd": 0,
			"read_only": 1,
			"depends_on": "eval:doc.location_type == 'Rack'",
			"description": "Auto-generated (e.g., R-I, R-II, R-III)"
		},
		{
			"fieldname": "shelf",
			"label": "Shelf",
			"fieldtype": "Link",
			"options": "Store Location",
			"description": "Select shelf within selected rack (required for Bin)",
			"reqd": 0,
			"depends_on": "eval:['Shelf', 'Bin'].includes(doc.location_type)"
		},
		{
			"fieldname": "shelf_name",
			"label": "Shelf Name",
			"fieldtype": "Data",
			"reqd": 0,
			"read_only": 1,
			"depends_on": "eval:doc.location_type == 'Shelf'",
			"description": "Auto-generated (e.g., S01, S02, S03)"
		},
		{
			"fieldname": "bin",
			"label": "Bin Name",
			"fieldtype": "Data",
			"reqd": 0,
			"read_only": 1,
			"description": "Auto-generated (e.g., B-A, B-B, B-C)",
			"depends_on": "eval:doc.location_type == 'Bin'"
		},
		
        
		{
			"fieldname": "section_tracking",
			"fieldtype": "Section Break",
			"label": "Additional Information",
			"collapsible": 1,
			"collapsed": 1
		},
		{
			"fieldname": "barcode",
			"label": "Barcode",
			"fieldtype": "Data",
			"unique": 1,
			"description": "Scannable barcode number"
		},
		{
			"fieldname": "qr_code",
			"label": "QR Code",
			"fieldtype": "Data",
			"unique": 1,
			"description": "QR code for mobile scanning"
		},
		{
			"fieldname": "column_break_tracking",
			"fieldtype": "Column Break"
		},
		{
			"fieldname": "description",
			"label": "Notes",
			"fieldtype": "Text Editor",
			"description": "Additional notes and information"
		},
		
        
		{
			"fieldname": "section_image",
			"fieldtype": "Section Break",
			"label": "Image",
			"collapsible": 1,
			"collapsed": 1
		},
		{
			"fieldname": "image",
			"label": "Location Image",
			"fieldtype": "Attach Image",
			"description": "Photo of the location"
		}
	],
	
	"permissions": [
		{
			"role": "Store Manager",
			"read": 1,
			"write": 1,
			"create": 1,
			"delete": 1,
			"select": 1,
			"report": 1,
			"export": 1
		},
		{
			"role": "Inventory Admin",
			"read": 1,
			"write": 1,
			"create": 1,
			"delete": 1,
			"select": 1,
			"report": 1,
			"export": 1
		},
		{
			"role": "Warehouse Staff",
			"read": 1,
			"write": 1,
			"create": 1,
			"select": 1,
			"report": 1
		},
		{
			"role": "Store Viewer",
			"read": 1,
			"select": 1,
			"report": 1
		}
	]
}
