"""
Demo Data: Store Items
Sample items covering different categories, tracking types, and configurations
"""

DEMO_ITEMS = [
	# Electrical Items
	{
		"item_name": "LED Bulb 9W",
		"item_group": "Electronics",
		"technical_category": "Electrical",
		"description": "<p>Energy efficient LED bulb, 9 watts, 800 lumens, warm white</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 1,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "WH-MAIN-A-R01-S1",
		"minimum_level": 50.0,
		"reorder_level": 75.0,
		"reorder_qty": 100.0,
		"maximum_level": 500.0,
		"standard_rate": 2.50,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "Electrical Cable 2.5mm²",
		"item_group": "Cables & Connectors",
		"technical_category": "Electrical",
		"description": "<p>Copper electrical cable, 2.5mm² cross-section, PVC insulated</p>",
		"default_uom": "Meter",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 1,
		"has_expiry_date": 0,
		"valuation_method": "Moving Average",
		"default_location": "WH-MAIN-A-R01-S2",
		"minimum_level": 100.0,
		"reorder_level": 200.0,
		"reorder_qty": 500.0,
		"maximum_level": 2000.0,
		"standard_rate": 1.25,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "3-Phase Motor 5HP",
		"item_group": "Electronics",
		"technical_category": "Electrical",
		"description": "<p>Industrial 3-phase induction motor, 5HP, 380V, 50Hz</p>",
		"default_uom": "Each",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 1,  # Serial tracked
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01",
		"minimum_level": 2.0,
		"reorder_level": 3.0,
		"reorder_qty": 5.0,
		"maximum_level": 10.0,
		"standard_rate": 450.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	
	# Mechanical Items
	{
		"item_name": "Bearing 6205",
		"item_group": "Spare Parts",
		"technical_category": "Mechanical",
		"description": "<p>Deep groove ball bearing, 6205 type, 25x52x15mm</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 1,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01-R1-C1",
		"minimum_level": 10.0,
		"reorder_level": 15.0,
		"reorder_qty": 25.0,
		"maximum_level": 100.0,
		"standard_rate": 5.50,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "V-Belt A-Type 1000mm",
		"item_group": "Spare Parts",
		"technical_category": "Mechanical",
		"description": "<p>V-belt type A, 1000mm length, for power transmission</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "Moving Average",
		"default_location": "STORE-01-R1-C2",
		"minimum_level": 5.0,
		"reorder_level": 8.0,
		"reorder_qty": 15.0,
		"maximum_level": 50.0,
		"standard_rate": 12.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	
	# Tools
	{
		"item_name": "Digital Multimeter",
		"item_group": "Measuring Tools",
		"technical_category": "Tool",
		"description": "<p>Digital multimeter, AC/DC voltage, current, resistance measurement</p>",
		"default_uom": "Each",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 1,  # Serial tracked
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01",
		"minimum_level": 2.0,
		"reorder_level": 3.0,
		"reorder_qty": 5.0,
		"maximum_level": 15.0,
		"standard_rate": 35.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "Adjustable Wrench 12inch",
		"item_group": "Hand Tools",
		"technical_category": "Tool",
		"description": "<p>Adjustable wrench, 12 inch, chrome vanadium steel</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "Moving Average",
		"default_location": "STORE-01",
		"minimum_level": 5.0,
		"reorder_level": 8.0,
		"reorder_qty": 10.0,
		"maximum_level": 30.0,
		"standard_rate": 15.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	
	# Consumables with Expiry
	{
		"item_name": "Loctite Thread Lock Blue",
		"item_group": "Chemicals",
		"technical_category": "Chemical",
		"description": "<p>Loctite 243 thread locking compound, medium strength, 50ml</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 1,
		"has_expiry_date": 1,  # Has expiry
		"shelf_life_days": 730,  # 2 years
		"valuation_method": "FIFO",
		"default_location": "STORE-01-R1-C1",
		"minimum_level": 10.0,
		"reorder_level": 15.0,
		"reorder_qty": 20.0,
		"maximum_level": 50.0,
		"standard_rate": 8.50,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "Industrial Lubricant Oil 5L",
		"item_group": "Lubricants",
		"technical_category": "Chemical",
		"description": "<p>Industrial grade lubricating oil, 5 liter can, ISO VG 68</p>",
		"default_uom": "Liter",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 1,
		"has_expiry_date": 1,  # Has expiry
		"shelf_life_days": 1095,  # 3 years
		"valuation_method": "FIFO",
		"default_location": "STORE-01-R1-C2",
		"minimum_level": 20.0,
		"reorder_level": 30.0,
		"reorder_qty": 50.0,
		"maximum_level": 200.0,
		"standard_rate": 12.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 1,  # Restricted - needs approval
		"enabled": 1,
	},
	
	# Hardware/Fasteners
	{
		"item_name": "Hex Bolt M10x50mm",
		"item_group": "Spare Parts",
		"technical_category": "Hardware",
		"description": "<p>Hex head bolt, M10 thread, 50mm length, grade 8.8, zinc plated</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "Moving Average",
		"default_location": "STORE-01-R1-C1",
		"minimum_level": 100.0,
		"reorder_level": 200.0,
		"reorder_qty": 500.0,
		"maximum_level": 2000.0,
		"standard_rate": 0.25,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "Hex Nut M10",
		"item_group": "Spare Parts",
		"technical_category": "Hardware",
		"description": "<p>Hex nut, M10 thread, grade 8, zinc plated</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "Moving Average",
		"default_location": "STORE-01-R1-C1",
		"minimum_level": 150.0,
		"reorder_level": 250.0,
		"reorder_qty": 500.0,
		"maximum_level": 3000.0,
		"standard_rate": 0.15,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	
	# Safety Equipment
	{
		"item_name": "Safety Helmet with Visor",
		"item_group": "Safety Equipment",
		"technical_category": "Safety",
		"description": "<p>Industrial safety helmet with clear visor, adjustable, EN 397 certified</p>",
		"default_uom": "Each",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 1,  # Serial tracked for accountability
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01",
		"minimum_level": 10.0,
		"reorder_level": 15.0,
		"reorder_qty": 25.0,
		"maximum_level": 100.0,
		"standard_rate": 18.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "Leather Work Gloves Pair",
		"item_group": "Safety Equipment",
		"technical_category": "Safety",
		"description": "<p>Industrial leather work gloves, reinforced palm, size L</p>",
		"default_uom": "Pair",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 1,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01",
		"minimum_level": 20.0,
		"reorder_level": 30.0,
		"reorder_qty": 50.0,
		"maximum_level": 200.0,
		"standard_rate": 6.50,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	
	# Office Supplies
	{
		"item_name": "A4 Copy Paper 500 Sheets",
		"item_group": "Office Supplies",
		"technical_category": "Office",
		"description": "<p>A4 size copy paper, 80 GSM, 500 sheets per ream, white</p>",
		"default_uom": "Pack",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01",
		"minimum_level": 10.0,
		"reorder_level": 20.0,
		"reorder_qty": 50.0,
		"maximum_level": 200.0,
		"standard_rate": 4.50,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	{
		"item_name": "Permanent Marker Black",
		"item_group": "Office Supplies",
		"technical_category": "Office",
		"description": "<p>Permanent marker pen, black ink, bullet tip</p>",
		"default_uom": "Piece",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 0,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "Moving Average",
		"default_location": "STORE-01",
		"minimum_level": 20.0,
		"reorder_level": 30.0,
		"reorder_qty": 50.0,
		"maximum_level": 200.0,
		"standard_rate": 0.75,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
	
	# Electronic Components
	{
		"item_name": "PLC Input Module 16CH",
		"item_group": "Components",
		"technical_category": "Electronic",
		"description": "<p>PLC digital input module, 16 channels, 24VDC, isolated</p>",
		"default_uom": "Each",
		"maintain_stock": 1,
		"is_stock_item": 1,
		"has_serial_no": 1,  # Serial tracked
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"valuation_method": "FIFO",
		"default_location": "STORE-01",
		"minimum_level": 2.0,
		"reorder_level": 3.0,
		"reorder_qty": 5.0,
		"maximum_level": 10.0,
		"standard_rate": 280.00,
		"is_purchase_item": 1,
		"is_returnable": 1,
		"is_restricted": 0,
		"enabled": 1,
	},
]
